export default {
  about: '',
  baseExperience: 0,
  baseHappiness: 0,
  baseStats: [],
  eggGroups: [],
  evolutionChainId: 0,
  evolutions: [],
  formSelected: '',
  genderRate: -1,
  genus: '',
  height: 0,
  id: '',
  image: '',
  isFavorite: false,
  isLoading: true,
  isLoadingEvolution: false,
  isShowModal: false,
  name: '',
  swiper: null,
  types: [],
  varieties: [],
  weight: 0
}
